---
title: "Research"
---

# {.tabset .tabset-fade}

## Education
**Ph.D. Political Science** -- University of Houston, (*expected 2022*)

* Dissertation: *Powerlessness and Antiestablishment Political Behavior*

                        Committee Members: Scott Clifford (Advisor), Elizabeth Simas, Ling Zhu, Scott Savage
  
* *Dissertation Completion Fellowship, 2021*

* *Dissertation Improvement Grant, 2020*

* *Lineberry Fellowship, 2017*

* *Presidential Graduate Fellowship, 2017*

**M.A. Political Science** -- Stony Brook University, State University of New York, 2015
  
**B.A. Political Science and Philosophy** -- William Paterson University, 2013

## Publications

* Clifford, Scott, Yongkwang Kim, and **Brian W. Sullivan** (2019). "An Improved Question Format for Measuring Conspiracy Beliefs." *Public Opinion Quarterly.* 83(4): 690-722. https://doi.org/10.1093/poq/nfz049

* Ozer, Adam L., **Brian W. Sullivan**, and Douglas Scott Van. "Viewed from Different Engels: Differences in Perceptions of Millennial Socialism Between Liberals and Conservatives." (Accepted for publication at *Political Research Quarterly*)

## Working Papers

* Clifford, Scott and **Brian W. Sullivan**. “Are We Measuring or Spreading Conspiracy Beliefs?” [Under review at *Political Science Research and Methods*]

* **Sullivan, Brian W.** "Does Control Influence the Endorsement of Conspiracy Theories?: A Reinvestigation of Lacking Control, Blame, and Conspiracy Theory Beliefs." [Manuscript development]

* **Sullivan, Brian W.** "Retaking Control in American Politics: The Relationship Between Status Threat, Powerlessness, and Populism." [Manuscript development]

* **Sullivan, Brian W.** "When All Else Fails": Violent Tendencies of the Politically Powerless." [Manuscript Development]

* **Sullivan, Brian W.** "Utilizing Split Matrices When Using Reversed Scored Scales to Improve Survey Reliability." [Manuscript development]

## CV

My Google scholar page can be found here: https://scholar.google.com/citations?user=6zhmXrMAAAAJ&hl=en

A PDF of my CV can be found here: 

```{r echo=FALSE}
xfun::embed_file('/Users/briansullivan/Desktop/Resumes/Vita_Sullivan.pdf')
```