---
title: "Resume"
---

# {.tabset .tabset-fade}

## Experience
<span style="text-decoration:underline">**Evaluation Specialist -- Foreign Services Institute, U.S. Department of State, June 2022-Present**</span>

* Design, program, and monitor surveys and dashboards for 8+ evaluation courses with more than 75+ students weekly. 

* Implement standardized attitudinal and behavioral evaluation survey questions for single and multi-week training courses. 

* Define survey best practices for stakeholders to establish efficient processes for data collection and analysis.

* Audit survey practices and develop multi-staged methodological improvement plans. 

* Co-lead implementation of Qualtrics quantitative and qualitative survey analysis and dashboard creation.

* Co-direct departmental migration of survey implementation from Survey Monkey to Qualtrics. 

<span style="text-decoration:underline">**Principal Investigator -- Powerlessness and Anti-Establishment Political Behavior, University of Houston, March 2019-May 2022**</span>

* Planned, built, and executed 3 end-to-end original research projects around current health of American democracy.

* Crafted grant proposals, novel survey measures, and experiments for diverse sampling populations through CloudResearch, MTurk, and Lucid recruiting platforms.

* Communicated the significance of findings in relevant academic journals and conferences.

<span style="text-decoration:underline">**Quantitative Researcher -- U.S. Study of Political Behavior, University of Houston, August 2019-May 2022**</span>

* Managed 6+ independently run, multi-stage survey studies.

* Designed and analyzed 6+ single- and multi-wave, large-n surveys that investigate growing trends in misinformation, conspiracy theories, polarization, and partisanship and how/if researchers affect these attitudes with survey exposure.

* Developed, programmed, and deployed survey experiments, including hand-coded conjoint designs.

* Presented findings to peers at local and national academic conferences.

* Designed and published 20+ novel survey questions about conspiratorial rumors and misinformation.

<span style="text-decoration:underline">**Quantitative Researcher -- U.S. Study of Misinformation & Conspiracy Theories, University of Houston, August 2017-July 2019**</span>

* Designed and edited 20+ novel survey questions about conspiratorial rumors and misinformation.

* Created and programmed survey logic using Qualtrics. 

* Presented findings to peers at a local and national academic conference.

* Published findings in industry-leading public opinion journal.

<span style="text-decoration:underline">**Graduate Research and Teaching Assistant, University of Houston, August 2017-August 2021**</span>

* Collected, coded, and analyzed 5+ data sets regarding state and federal level election records.

* Assisted in planning the *Political Misperceptions* academic conference held at the University of Houston.

* Designed, edited, and coded 20+ surveys given to nationally represented U.S. Adults.

* Developed, moderated, and graded weekly, midterm and final assignments for 200+ undergraduate and graduate students.

<span style="text-decoration:underline">**Associate Editor, WebMD/Medscape Education, October 2016-July 2017**</span>

* Formatted and edited PowerPoint slide decks for content and style for Medscape’s education website that is accessed by medical doctors worldwide. 

* Recreated statistical graphs from peer-reviewed medical journals for original PowerPoint decks.

* Established statistical and scientific methodology practices for entire editorial team.

## Skills
<span style="text-decoration:underline">**Quantitative Analysis**</span>

* Online survey sampling and design, programming, and implementation

* Online and Lab-based experimental and quasi-experimental sampling and design, programming, and implementation

* Behavioral data analysis

* Causal inference

* Multivariate analysis

* Probability

* Significance testing

<span style="text-decoration:underline">**Programming Languages**</span>

* R (GNU S)

* R-Studio

* Qualtrics (XM, 360, and Dashboard design)

* LaTeX

* Python

* HTML

* JavaScript

* WordPress

* Microsoft Office

* Adobe Creative Suites

<span style="text-decoration:underline">**Certification**</span>

* Human Research - Social-Behavioral-Educational Researchers Certificate at CITI Program

* Responsible Conduct of Research - Social and Behavioral Responsible Conduct of Research Course Certificate at CITI Program

* Conflict of Interest Course - Conflict of Interest in Research Course Certificate at CITI Program

<span style="text-decoration:underline">**Research Experience**</span>

* 7+ years experience of quantitative data collection and analysis.

## Resume PDF

A pdf of my resume can be found here: 

```{r echo=FALSE}
xfun::embed_file('/Users/briansullivan/Desktop/Resumes/B_Sullivan_resume.pdf')
```

